### ISSUE TITLE
Dist failure due to symlink that doesn't point anywhere

### ISSUE THREAD

**Issue by jobywalker** [rgov/starter-pack#7]
When I do a build I get a failure to zip up the entire package because of the dead symlink in the DF SDL: df/libs/SDL_image.framework/Frameworks

`Compressing pack...
Traceback (most recent call last):
  File "./main.py", line 19, in <module>
    stage.main()
  File "/Volumes/Imperium/starter-pack/starterpack/dist.py", line 97, in main
    zip_pack()
  File "/Volumes/Imperium/starter-pack/starterpack/dist.py", line 60, in zip_pack
    zf.write(fname, os.path.relpath(fname, paths.build()))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 1688, in write
    zinfo = ZipInfo.from_file(filename, arcname)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 483, in from_file
    st = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: 'build/Dwarf Fortress 0.44.12/libs/SDL_image.framework/Frameworks'`

**Comment by rgov** [comment]
Yeah, this is the last step, and so I would just manually create a zip at the end after the error.

Python's ZipFile is pretty bad, and if I were re-writing this, I would have avoided using it.
